### PR TITLE
Add nix flake

### PR DESCRIPTION
**Pull request by yavko**
Features planned:
- [x] Overlay
- [x] Home Manager Module

### CODE REVIEW

**Comment by fdev31** [comment]
Thank you for the contribution!
I can't juge the nix things, but I would prefer to have it in a subfolder...
`packages/nix/` for instance...

**Comment by yavko** [comment]
> Thank you for the contribution!
> I can't juge the nix things, but I would prefer to have it in a subfolder...
> `packages/nix/` for instance...

Can't

Edit: actually it might be possible, but it's irregular, but I'll look into it

**Comment by yavko** [comment]
@fdev31 Done, also added some stuff to the readme if thats okay

**Comment by fdev31** [comment]
Great !
I'm ok with the README change except one thing: "nix" should be part of "installation" section, but it's a bit big to be at the very start...
I would keep it close (or even inside) the installation section... after changing the order, maybe we can start the README page with:

# Features
# Usage
# Installation
## "manual" / pip
## archlinux / pacman
## nix / Home manager
# Changelog
...

something like this ?

**Pull request merged**
